disabled_rules:
  - file_length
  - identifier_name
  - type_body_length
  - function_body_length
  - line_length
  - large_tuple
  - type_name
  - trailing_comma
  - closure_parameter_position

opt_in_rules:  
- missing_docs

missing_docs:
  error:    
  - open    
  - public    
  - internal    
  - fileprivate    
  - private    

allow_zero_lintable_files: true

reporter: "github-actions-logging"