//
//  MoleSegmentationTestView.swift
//  P8-Product
//
//  Created by Simon Thordal on 3/24/26.
//

import SwiftUI
import CoreML

// MARK: - Mole Segmentation View

/// A view that lets the user tap on a mole image to trigger SAM2.1 segmentation.
///
/// The image is displayed aspect-fit. When the user taps, a `cropSize × cropSize`
/// bounding box is centred on the tap and only that crop is sent to the model,
/// which keeps inference fast and improves accuracy for small moles.
/// The resulting mask is composited back at the bounding-box position.
struct MoleSegmentationTestView: View {

    // MARK: - Constants

    /// Side length of the square crop region sent to the model, in image pixels.
    private let cropSize: CGFloat = 200

    // MARK: - State

    /// The image to segment. Replace with the image captured by the camera.
    @State private var testImage: UIImage? = UIImage(named: "test_mole_image")

    /// The segmentation mask for the last bounding-box crop.
    @State private var cropMaskImage: UIImage?

    /// `true` while the segmentation pipeline is running.
    @State private var isProcessing = false

    /// Holds the localised error message when segmentation fails.
    @State private var errorMessage: String?

    /// Controls presentation of the error alert.
    @State private var showError = false

    /// The loaded model wrapper, initialised asynchronously on appear
    // TODO: - Make the model load as soon as the app is turned on
    @State private var segmentor: MoleSegmentor?

    /// The bounding box in *view* coordinates, used to position the box and mask overlay.
    @State private var boundingBox: CGRect?

    // MARK: - Body

    var body: some View {
        NavigationStack {
            ZStack {
                if let image = testImage {
                    imageContent(image: image)
                } else {
                    noImagePlaceholder
                }

                if isProcessing {
                    loadingOverlay
                }
            }
            .navigationTitle("Mole Segmentation")
            .toolbar { toolbarContent }
            .alert("Error", isPresented: $showError) {
                Button("OK") { showError = false }
            } message: {
                Text(errorMessage ?? "Unknown error")
            }
            .task { await loadSegmentor() }
        }
    }

    // MARK: - Subviews

    /// Renders the base image together with the bounding-box rectangle and mask overlay.
    ///
    /// The view is laid out with `scaledToFit`, so a `GeometryReader` is used to calculate
    /// the actual displayed image size and offset needed to convert between
    /// view coordinates and image-pixel coordinates.
    @ViewBuilder
    private func imageContent(image: UIImage) -> some View {
        GeometryReader { geometry in
            ZStack {
                // The image of the mole
                Image(uiImage: image)
                    .resizable()
                    .scaledToFit()
                    .frame(width: geometry.size.width, height: geometry.size.height)
                // Bounding box after click
                if let box = boundingBox {
                    Rectangle()
                        .stroke(Color.yellow, lineWidth: 2)
                        .frame(width: box.width, height: box.height)
                        .position(x: box.midX, y: box.midY)
                }
                // Mask generated by the SAM model
                if let mask = cropMaskImage, let box = boundingBox {
                                    Image(uiImage: mask)
                                        .resizable()
                                        .frame(width: box.width, height: box.height)
                                        .position(x: box.midX, y: box.midY)
                                }
            }
            .contentShape(Rectangle())
            .onTapGesture { location in
                // Call the SAM processing when we click anywhere in the image
                handleTap(at: location, in: geometry.size, image: image)
            }
        }
    }

    // MARK: - Actions

    /// Converts a tap in view coordinates to image-pixel coordinates, builds the
    /// bounding-box crop, runs segmentation, and updates the overlay.
    ///
    /// - Parameters:
    ///   - location: The tap position in the view's coordinate space.
    ///   - viewSize: The size of the `GeometryReader` frame containing the image.
    ///   - image: The full source image.
    private func handleTap(at location: CGPoint, in viewSize: CGSize, image: UIImage) {
        guard let segmentor, let cgImage = image.cgImage else { return }
        guard !isProcessing else { return }

        let pixelW = CGFloat(cgImage.width)
        let pixelH = CGFloat(cgImage.height)

        // Create coordinate converter
        let converter = ImageCoordinateConverter(
            imageSize: CGSize(width: pixelW, height: pixelH),
            viewSize: viewSize
        )

        // Map the tap from view space to image-pixel space
        let tapPixel    = converter.viewToPixel(location)
        // Build a square crop around the tap point
        let boxPixel    = converter.croppingRect(around: tapPixel, cropSize: cropSize)
        // Express the tap relative to the crop origin (used as the SAM prompt point)
        let pointInCrop = converter.pointInRect(tapPixel, relativeTo: boxPixel)
        // Map the crop box back to view space for the SwiftUI overlay
        boundingBox = converter.pixelRectToView(boxPixel)

        Task {
            isProcessing = true
            do {
                // Crop the source image to the bounding box
                guard let croppedCG = cgImage.cropping(to: boxPixel) else {
                    throw PipelineError.invalidImage
                }
                // Run SAM segmentation on the crop
                let croppedImage = UIImage(cgImage: croppedCG)
                let maskArray    = try await segmentor.segment(image: croppedImage,
                                                               point: pointInCrop,
                                                               modelSize: 1024)
                // Convert the raw mask tensor to a displayable overlay image
                let maskImage    = try maskRenderer.render(maskArray, targetSize: boxPixel.size)

                await MainActor.run {
                    cropMaskImage = maskImage
                    isProcessing  = false
                }
            } catch {
                await MainActor.run {
                    errorMessage = "Segmentation failed: \(error.localizedDescription)"
                    showError    = true
                    isProcessing = false
                }
            }
        }
    }

    /// Loads the Edge-SAM model asynchronously. Called once on view appear.
    private func loadSegmentor() async {
        do {
            segmentor = try await MoleSegmentor()
        } catch {
            errorMessage = "Failed to load model: \(error.localizedDescription)"
            showError = true
        }
    }

    /// Removes the current mask overlay, bounding box, and tap indicator,
    /// and clears the model's image-embedding cache.
    private func clearSegmentation() {
        cropMaskImage = nil
        boundingBox   = nil
        segmentor?.clearCache()
    }

    // MARK: - Helpers

    private let maskRenderer = MaskRenderer()

    // MARK: - Supporting Views

    /// Full-screen overlay shown while the pipeline is running.
    private var loadingOverlay: some View {
        ZStack {
            Color.black.opacity(0.3).ignoresSafeArea()
            VStack(spacing: 16) {
                ProgressView().scaleEffect(1.5)
                Text("Segmenting...")
                    .foregroundStyle(.white)
                    .font(.headline)
            }
            .padding()
            .background(.black.opacity(0.7))
            .clipShape(RoundedRectangle(cornerRadius: 12))
        }
    }

    /// Shown in place of the image when `testImage` is `nil`.
    private var noImagePlaceholder: some View {
        VStack(spacing: 20) {
            Image(systemName: "photo")
                .font(.system(size: 60))
                .foregroundStyle(.secondary)
            Text("No test image found")
                .font(.headline)
            Text("Add an image named 'test_mole_image' to Assets.xcassets")
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .padding()
        }
    }

    /// Navigation bar buttons and debug info.
    @ToolbarContentBuilder
    private var toolbarContent: some ToolbarContent {
        ToolbarItem(placement: .navigationBarTrailing) {
            Button("Clear") { clearSegmentation() }
                .disabled(cropMaskImage == nil)
        }
    }
}

// MARK: - Preview

#Preview {
    MoleSegmentationTestView()
}
